name: aldayat_screens
description: Aldayat project.

publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  network_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  printing: ^5.11.1
  responsive_grid: ^2.4.4
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  syncfusion_flutter_charts: ^23.1.44
  url_launcher: ^6.2.1

  # cupertino_icons: ^1.0.2
  # lottie: ^1.4.3
  # get: ^4.6.5
  # google_fonts: ^3.0.1
  # responsive_grid: ^2.1.0
  # http: ^0.13.5
  # intl: ^0.17.0
  # url_launcher: ^6.1.6
  # flutter_launcher_icons: ^0.12.0
  # hive: ^2.2.3
  # shimmer: ^2.0.0
  # fl_chart: ^0.55.2
  # # just_audio: ^0.9.30
  # network_info_plus: ^3.0.1
  # syncfusion_flutter_charts: ^20.4.38
  # sqflite_common_ffi: ^2.2.0+1
  # path: ^1.8.2
  # sqflite: ^2.2.3
  # path_provider: ^2.0.11
  # printing: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/download.png"
  windows:
    generate: true
    image_path: "lib/assets/download.png"
    icon_size: 48

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  
flutter_native_splash:
  color: 
  image_web: lib/assets/download.png
  fonts:
    - family: Mine
      fonts:
        - asset: lib/assets/ArabicUIDisplayBlack.otf
  
  
  
  
  
  
  
  
  
  
